name: GitHub Actions Demo
on: [push]
jobs:
  Checkout-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: jest --passWithNoTests --silent --noStackTrace --runInBand -c jest-unit-config.js
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}